### ISSUE TITLE
Add missing __version__ attribute

### ISSUE THREAD

**Issue by jchabloz** [Nicoretti/crc#58]
First of all, thank you for this great package! I use it extensively and it works more than fine for me...

As a minor inconvenience, I have seen that there are no `__version__` attribute existing anymore, which bothered me while I was trying to perform some test on it to improve the portability of some of my code to older systems. Solved this with a `try`/`catch`, but it is not ideal at all. I think it would be good practice to have a `__version__` value against which to test, especially when some features/functions are not back-compatible :-)

**Comment by Nicoretti** [comment]
Hi Jérémie,

thank you for your appreciation and feedback.


Let me quickly explain why I did remove the `__version__` field.

From my point of view, it is a important to have a single source of truth for the package
metadata, like the version. Otherwise one may end up creating a release where the version shown by the package manager (pip) differs from the version reported by the package (`__version__`).

For sure there are solutions to this problem, like using `pyproject.toml` as the 
single source of truth and adding some automated checks/updates. Still the margin
for error and the effort of maintanance increases.

Additionaly starting with python 3.8 [a new mechansim to access package metadata](https://docs.python.org/3.8/library/importlib.metadata.html?highlight=metadata#module-importlib.metadata) was introduced.
Using this new mechanism you may be able to addresses your issue (see code snippet below),
if not please let me know.


```python
>>> from importlib import metadata
>>> metadata.version('crc')
'3.0.0'
```

Best
Nico

**Comment by jchabloz** [comment]
Hello Nicola,

Thanks for your detailed answer. I understand your point concerning properly maintaining the single source for the version number. To be honest, I never even thought about it before...
I was not aware of the relatively new metadata mechanism and will try it out. It won't completely solve my portability issue in all cases, but anyway, it is more of an inconvenience than a real issue!
I will close this issue.

Jérémie
